(define (problem replan_1)
  (:domain replanv)
  (:objects
    r2d2 - robot
    wp1 wp2 wp3 wp4 wp5 wp6 wp7 wp8 - waypoint
    obj1 obj2 obj3 - piece
  )
  (:init
    (connected wp1 wp2)
    (connected wp2 wp1)
    ( = (nav_time wp1 wp2) 1)
    ( = (nav_time wp2 wp1) 1)
    (connected wp1 wp3)
    (connected wp3 wp1)
    ( = (nav_time wp1 wp3) 1)
    ( = (nav_time wp3 wp1) 1)
    (connected wp4 wp2)
    (connected wp2 wp4)
    ( = (nav_time wp4 wp2) 1)
    ( = (nav_time wp2 wp4) 1)
    (connected wp4 wp3)
    (connected wp3 wp4)
    ( = (nav_time wp4 wp3) 1)
    ( = (nav_time wp3 wp4) 1)

    (connected wp5 wp6)
    (connected wp6 wp5)
    ( = (nav_time wp5 wp6) 1)
    ( = (nav_time wp6 wp5) 1)
    (connected wp5 wp7)
    (connected wp7 wp5)
    ( = (nav_time wp5 wp7) 1)
    ( = (nav_time wp7 wp5) 1)
    (connected wp8 wp6)
    (connected wp6 wp8)
    ( = (nav_time wp8 wp6) 1)
    ( = (nav_time wp6 wp8) 1)
    (connected wp8 wp7)
    (connected wp7 wp8)
    ( = (nav_time wp8 wp7) 1)
    ( = (nav_time wp7 wp8) 1)

    (connected wp4 wp7)
    (connected wp7 wp4)
    ( = (nav_time wp4 wp7) 2)
    ( = (nav_time wp7 wp4) 2)
    (connected wp2 wp5)
    (connected wp5 wp2)
    ( = (nav_time wp2 wp5) 2)
    ( = (nav_time wp5 wp2) 2)

    (robot_at r2d2 wp1)
    (robot_available r2d2)

    (piece_at obj1 wp4)
    (piece_at obj2 wp1)
    (piece_at obj3 wp6)
  )

    (:goal (and
      (piece_at obj1 wp8)
      (piece_at obj2 wp2)
      (piece_at obj3 wp3)
    ))
  )
