move:
  ros__parameters:
    plugins:
      - plansys2_move_bt_node
    waypoints: ["wp1", "wp2", "wp3", "wp4", "wp5", "wp6", "wp7", "wp8"]
    waypoint_coords:
      wp1: [0.0, 0.0, 0.0]
      wp2: [1.0, 0.0, 0.0]
      wp3: [0.0, 1.0, 0.0]
      wp4: [1.0, 1.0, 0.0]
      wp5: [2.0, 0.0, 0.0]
      wp6: [3.0, 0.0, 0.0]
      wp7: [2.0, 1.0, 0.0]
      wp8: [3.0, 1.0, 0.0]
pick:
  ros__parameters:
    plugins:
      - plansys2_open_gripper_bt_node
      - plansys2_close_gripper_bt_node
      - plansys2_approach_object_bt_node
place:
  ros__parameters:
    plugins:
      - plansys2_open_gripper_bt_node
      - plansys2_close_gripper_bt_node

llm_replan_controller:
  ros__parameters:

    self_reflector_context: 'You are an expert assistant in robotics behavior evaluation, pattern recognition, and environmental forecasting in a robotics context.
                             Your objective is to evaluate robot performance by analyzing its behavior and environmental changes. You will:
                              - Forecast and anticipate environmental factors related to the execution of the robots actions.
                              - Provide a short analysis for future robot plans.

                             The current scenario involves a robot navigating a graph of waypoints. The waypoints are distributed as follows:
                              (0,4) wp3 --- wp4 --- wp7 --- wp8 (6,4)
                                    |       |       |       |
                              (0,2) wp1 --- wp2 --- wp5 --- wp6 (6,2)

                             At each waypoint, the robot must pick up pieces and place them at desired locations dictated by its goal. The robot is only allowed to move to a waypoint if it is connected.
                             The environment is described using the PDDL standard, and the initial domain is the following: {domain}.You will be provided with the robots current state (in the form of a PDDL problem)
                             and the current plan. Your task is to forecast how the environment will change and how it will affect the robots actions. Based on this forecast, you will describe the possible future changes.

                             For forecasting, pay close attention to the predicates in each problem provided. These predicates will likely change over time. Changes to the environment are reflected as updates to the PDDL problem.

                             Your answer must be in JSON format, following this schema:

                             Result = {"improvement_feedback": str}

                             an example of the JSON schema is the following:
                             {"improvement_feedback": "Based on the the changes in the domain it is seems that the waypoints wp1 and wp2 will be disconnected in 10 seconds,
                                                        and the current plan tells the robot to move to wp2. It is recommended to change the plan to avoid the disconnection."}
                             {"improvement_feedback": "Even though the robot a disconection will be likely to happen in the future, the robot is not going to be affected by it
                                                        since the robot is not going to move to that waypoint. It is recommended to keep the current plan."}'

                             
    self_reflector_information_input: 'You will now have to try to forecast how the environment will change and how it will affect the current robot plan.
                                       Remember to play cose attention to the predicates and how they change over time to provide a strong analysis.
                                       The current robot state is the following: {problem}.
                                       The current robot plan is the following: {current_plan}.
                                       Please Do not use markdown, only the JSON schema is allowed.
                                      '
    replanner_expert_context: 'You are a robotics planner expert, with vast expierience using PDDL. Your job is to evaluate two PDDL plans and decide which one is the best.
                               the two plans; one the current plan being executed and an alternative feaseble plan; will be linked to the same robot scenario, where the robot
                               has to navigate in a graph of waypoints.
                               The waypoints are distributed as follows:
                                            (0,4) wp3 --- wp4 --- wp7 --- wp8 (6,4)
                                                  |       |       |       |
                                            (0,2) wp1 --- wp2 --- wp5 --- wp6 (6,2)
                                In each waypoint the robot has to pick up pieces, and place them at desired locations dictated by the goal. The robot is only allowed to move to a
                                waypoint if it is connected. In more detail the environment is described using the PDDL standard and the initial domain is the following: {domain}.
                                The initial robot goal is the following: {goal}. and the initial pddl problem is the following: {problem}. It is neccesary for you to know that the
                                environment is not static and will likely change over time. For that reason you will be provided a feedback stating how the plan you decided to use 
                                affected the robot performance based on the real environment changes.
                                You will be provided with the textual analysis of the possible future changes in the environment. You will use 
                                the analysis as a hint and decide if you should use the current plan or the alternative plan.
                                Your answer will be in the format of a JSON with the following schema:
                                Result = {"should_use_alternate_plan": bool, "reason": str}
                                where should_replan is a boolean indicating if the new plan is the best or not, replan_reason is a string explaining why the new plan is better or NOT.
                                Only the JSON schema is allowed, please do not use markdown format. 

                                an example of the JSON schema is the following:
                                {"should_use_alternate_plan": true, "reason": "The robot is not able to reach the desired waypoint with the current plan"}
                                {"should_use_alternate_plan": false, "reason": "The robot is able to reach the desired waypoint, the current plan is the best option."}                    
                                '
    replanner_expert_information_input: 'You must decide which plan is the best given the context. Use the textual analysis as a hint for your decision. The environment
                                         is dynamic and will likely change over time. Even though neither plan may perfectly reflect future environmental changes, you 
                                         must choose between the two given plans. Neither of the plans can be altered or improved, and no other options are available.
                                         The textual analysis is the following: {feedback}.
                                         The current plan is the following: {current_plan}.
                                         The new alternative plan is the following: {new_plan}.
                                         Please Do not use markdown, only the JSON schema is allowed.
                                      '
                
planning_node:
  ros__parameters:
    env_api_key: MISTRAL_API_KEY
    model_provider: mistral
    model_name: mistral-large-latest
    top_p: 1.0
    temperature: 0.0
    max_tokens: 1000
