move:
  ros__parameters:
    plugins:
      - plansys2_move_bt_node
    waypoints: ["wp1", "wp2", "wp3", "wp4", "wp5", "wp6", "wp7", "wp8"]
    waypoint_coords:
      wp1: [0.0, 0.0, 0.0]
      wp2: [1.0, 0.0, 0.0]
      wp3: [0.0, 1.0, 0.0]
      wp4: [1.0, 1.0, 0.0]
      wp5: [2.0, 0.0, 0.0]
      wp6: [3.0, 0.0, 0.0]
      wp7: [2.0, 1.0, 0.0]
      wp8: [3.0, 1.0, 0.0]
pick:
  ros__parameters:
    plugins:
      - plansys2_open_gripper_bt_node
      - plansys2_close_gripper_bt_node
      - plansys2_approach_object_bt_node
place:
  ros__parameters:
    plugins:
      - plansys2_open_gripper_bt_node
      - plansys2_close_gripper_bt_node

llm_replan_controller:
  ros__parameters:

    self_reflector_context: 'You are an expert assistant in robotics behavior evaluation, pattern recognition, and environmental forecasting in a robotics context.
                             Your objective is to evaluate robot performance by analyzing its behavior and environmental changes. You will:
                              - Forecast and anticipate environmental factors related to the execution of the robots actions.
                              - Provide improvement feedback analysis for future robot actions.

                             The current scenario involves a robot navigating a graph of waypoints. The waypoints are distributed as follows:
                              (0,4) wp3 --- wp4 --- wp7 --- wp8 (6,4)
                                    |       |       |       |
                              (0,2) wp1 --- wp2 --- wp5 --- wp6 (6,2)

                             At each waypoint, the robot must pick up pieces and place them at desired locations dictated by its goal. The robot is only allowed to move to a waypoint if it is connected.
                             The environment is described using the PDDL standard, and the initial domain is the following: {domain}.You will be provided with the robots current state (in the form of a PDDL problem)
                             and the current plan.Your task is to forecast how the environment will change and how it will affect the robots actions. Based on this forecast, you will provide feedback analysis to improve the robots performance.

                             For forecasting, pay close attention to the predicates in each problem provided. These predicates will likely change over time. Changes to the environment are reflected as updates to the PDDL problem.

                             Your answer must be in JSON format, following this schema:

                             Result = {"improvement_feedback": str}

                             an example of the JSON schema is the following:
                             {"improvement_feedback": "Based on the the changes in the domain it is seems that the waypoints wp1 and wp2 will be disconnected in 10 seconds,
                                                        and the current plan tells the robot to move to wp2. It is recommended to change the plan to avoid the disconnection."}
                             {"improvement_feedback": "Even though the robot a disconection will be likely to happen in the future, the robot is not going to be affected by it
                                                        since the robot is not going to move to that waypoint. It is recommended to keep the current plan."}'

                             
    self_reflector_information_input: 'You will now have to provide a feedback taken into account the past environment changes and the robot performance.
                                      The current robot state is the following: {problem}.
                                      The current robot plan is the following: {current_plan}.
                                      You will have to provide a feedback analysis to improve the robot performance.
                                      Please Do not use markdown, only the JSON schema is allowed.
                                      '
    replanner_expert_context: 'You are a robotics planner expert, with vast expierience using PDDL. Your job is to evaluate two PDDL plans and decide which one is the best.
                               the two plans; one the current plan being executed and an alternative feaseble plan; will be linked to the same robot scenario, where the robot
                               has to navigate in a graph of waypoints.
                               The waypoints are distributed as follows:
                                            (0,4) wp3 --- wp4 --- wp7 --- wp8 (6,4)
                                                  |       |       |       |
                                            (0,2) wp1 --- wp2 --- wp5 --- wp6 (6,2)
                                In each waypoint the robot has to pick up pieces, and place them at desired locations dictated by the goal. The robot is only allowed to move to a
                                waypoint if it is connected. In more detail the environment is described using the PDDL standard and the initial domain is the following: {domain}.
                                The initial robot goal is the following: {goal}. and the initial pddl problem is the following: {problem}. It is neccesary for you to know that the
                                environment is not static and will likely change over time. For that reason you will be provided a feedback stating how the plan you decided to use 
                                affected the robot performance based on the real environment changes.
                                You will be provided with the textual analysis of the possible future changes in the environment. You will use 
                                the analysis as a hint and decide if you should use the current plan or the alternative plan.
                                Your answer will be in the format of a JSON with the following schema:
                                Result = {"should_change_plan": bool, "reason": str}
                                where should_replan is a boolean indicating if the new plan is the best or not, replan_reason is a string explaining why the new plan is better or NOT.
                                Only the JSON schema is allowed, please do not use markdown format. 

                                an example of the JSON schema is the following:
                                {"should_change_plan": true, "reason": "The robot is not able to reach the desired waypoint"}
                                {"should_change_plan": false, "reason": "The robot is able to reach the desired waypoint"}                    
                                '
    replanner_expert_information_input: 'You will now have to decide which plan is the best using the textual analysis as a hint of what is likely to change in the future.
                                        The textual analysis is the following: {feedback}.
                                        The current plan is the following: {current_plan}.
                                        The new alternative plan is the following: {new_plan}.
                                        Please Do not use markdown, only the JSON schema is allowed.
                                      '

    llm_context: 'You are a robotics planner expert, with a lot of experience in the field and using PDDL
                  You are aslo an expert in pattern recognition and environmental analysis such as cyclical patterns, and other factors that could affect the robot action execution.
                 The current robotic scenario is a robot navigating in a graph of waypoints.
                 The waypoints are distributed as follows:
                              (0,4) wp3 --- wp4 --- wp7 --- wp8 (6,4)
                                     |       |       |       |
                              (0,2) wp1 --- wp2 --- wp5 --- wp6 (6,2)
                 In each waypoint the robot has to pick up pieces, and place them at desired locations.
                 The navigation time between waypoints is a calculated value, and all actions are durative, reflecting their execution over time.
                 The robot is ONLY allowed to move to a waypoint if it is connected to the current robot waypoint
                 The robot should move to a waypoint if it has to pick or place an object there or is in the path to the desired waypoint.
                 the initial pddl domain is the following: {domain}.
                 The initial robot goal is the following: {goal}.
                 The initial pddl problem is the following: {problem}.
                 Your work is to asses the current state of the robot which will be presentd to you in the form of the a pddl problem history, goal, and current remaining plan of the robot
                 and an alternative feasible plan will be given to you. And you have to compare and assest it, providing  an explanation of why you should use or not the new plan.
                 You can take into account context aware information factors like energy, environmental uncertainty, and other factors that could affect the robot action execution.
                 You will be also in charge of predict changes in the environment, try to detect patterns in the environment and
                 anticipate environmental changes that could affect the robot action execution. Remember that the changes are displayed as changes to the pddl problem.
                 in the following problem [timestamp(ns)][aidition/removal][predicate] if not modification has happend you will receive the current problem pddl.
                 Such as [1000000][added][connected wp1 wp2] or [2000000][removed][connected wp1 wp2]
                 keep special attention and track changes in the predicates of the pddl problem history.
                 In order for your environment analysis to be successful you should
                 provide a new prediction to anticipate the environmental changes that could affect the robot action execution. 
                 Based on that prediction you will have to come up with a new pddl problem reflecting the anticipated changes in the environment.
                 Take special attention to the connected and disconected waypoints in the environment and try to anticipate changes in the environment.
                 you will be provided with the state of the robot in form the pddl problem modifications history, you will be also given
                 the current goal, remaining plan and an alternative new feasible plan for you to compare with.
                 you should provide the answer in the form of JSON with the following JSON schema:
                 Result = {"should_replan": bool, "replan_reason": str, "new_pddl_problem": str, "environment_prediction": str}
                 where should_replan is a boolean indicating if the new plan is better or not, replan_reason is a string explaining why the new plan is better or NOT, new_pddl_problem is a string with the pddl problem
                 reflecting the ancitipated changes in the environment.
                 The new_pddl_problem should not include terms such as \n or \t,
                 environment_prediction is a string with the anticipation in the environment you have made.
                 Here are some examples of the result JSON:
                 {"should_replan": true, "replan_reason": "The robot is not able to reach the desired waypoint", "new_pddl_problem": "(define (problem robot-problem) (:domain robot-domain) (:objects ...)" "environment_prediction": "the connection will be lost between wp1 and wp2 in 10 seconds"}
                 {"should_replan": true, "replan_reason": "The robot is not able to reach the desired waypoint", "new_pddl_problem": "(define (problem robot-problem) (:domain robot-domain) (:objects ...)" "environment_prediction": "The environment will likely to mantain static"}

                 Please Do not use markdown, only the JSON schema is allowed.
                 Please do not include terms such as \n or \t in the JSON schema.
                 
                 Return: Result'

    prompt_template: 'As a robotics planner expert you will now assest the current robot  state and decide if the alternative plan is better.
                  as well as anticipate and evaluate environmental changes that could affect the robot action execution.
                  The problem the following: {problem_history}.
                  The current robot goal is the following: {goal}.
                  The remaining current plan is the following: {current_plan}.
                  The new alternative feasible plan is the following: {new_plan}.

                  Please Do not use markdown, only the JSON schema is allowed.
                 
                  '
                
planning_node:
  ros__parameters:
    env_api_key: MISTRAL_API_KEY
    model_provider: mistral
    model_name: mistral-large-latest
    top_p: 1.0
    temperature: 0.0
    max_tokens: 1000
